name: Build and Deploy

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

  # Run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch for deployment'
        required: true
        default: 'gh-pages'
      folder:
        description: 'Folder to deploy'
        required: true
        default: 'website/build'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Initialize Flask .env file
      run: |
        python init_env.py
    - name: Build Frozen-Flask web application
      run: |
        python build.py
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: website/build
